repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^notebooks/
      - id: end-of-file-fixer
        exclude: ^notebooks/
      - id: check-yaml
        exclude: ^notebooks/
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix]
        exclude: ^notebooks/
      - id: ruff-format
        exclude: ^notebooks/
